version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/task-management
      - NODE_ENV=development
      - JWT_SECRET=abc123def456ghi789jkl
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 